### ISSUE TITLE
Auto-gen implementation

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#11]
Making a PR of the auto-generator now. Where do you want it placed? IMHO it should be accessible as `Hedgehog.Gen.auto`, but the implementation is fairly substantial, so I'm wondering if it should be placed in its own file (and if so, how to do that considering that Hedgehog.Gen is already defined in Gen.fs) or if it's okay to have everything in Gen.fs (which might be the only option).

**Comment by moodmosaic** [comment]
I think, it'll be fine to have this together with all the other generators. No worries about being huge in terms of source lines of code.
