### ISSUE TITLE
Add reference to Hedgehog

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#2]
There needs to be a reference to the main Hedgehog library. I don't know what kind of constraints you want on the version number, so I'll leave it to you.

**Comment by moodmosaic** [comment]
Good catch. It should always be the latest version.

**Comment by cmeeren** [comment]
Great. Do you want to add it? I'm not used to Paket.

**Comment by moodmosaic** [comment]
@cmeeren, basically you add the NuGet Package name in `paket.template` and `paket.references` and then let Paket know about it by running `.paket/paket.exe install` which takes care of everything else.

I've just opened #3, so you can also have it as an example. Once it's merged, you can pull the latest from `master` branch, run `./build.sh` and you should be good to go.

**Comment by moodmosaic** [comment]
@cmeeren, if you're blocked waiting for #3 to be merged, we can go ahead and merge it right away, else we can wait for @jystic first to give it a 👍

**Comment by cmeeren** [comment]
Yes, I'm blocked by #3, though I'm not in a hurry. :)

**Comment by cmeeren** [comment]
Could you also add a reference to the test project?

**Comment by moodmosaic** [comment]
Could you do it as part of one of those forthcoming PRs you have? Otherwise I can do it myself during the day.

**Comment by cmeeren** [comment]
Sure :)

**Comment by cmeeren** [comment]
Oh, nevermind - it was already added, I just forgot to rebuild the test project (I'm used to nuget, where VS does a lot automatically for you.)
