### ISSUE TITLE
Remove unit parameter from auto

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#22]
Since `auto<'a>()` has an explicit type parameter, I think it's possible to remove the unit parameter (if it's possible, then IMHO we should do it since it's just unnecessary noise). It compiled fine when I tried it, and all tests completed successfully.

Waiting with PR until after #21 is merged due to conflicts.

**Comment by moodmosaic** [comment]
:+1:

**Comment by moodmosaic** [comment]
Actually, does it have the same exact type when you remove the `()`?

**Comment by cmeeren** [comment]
Type? If you mean signature, then no; it changes from `unit -> Gen<'a>` to just `Gen<'a>`.

**Comment by cmeeren** [comment]
Just to prove that it works, I tested the following:

```f#
let rnd = System.Random()
let foo<'a> = rnd.Next()
```

`foo` has type int, but calling `foo` or `foo<_>` generates new values each time. In other words, the function value is not cached when there are type parameters (as it is for completely parameterless functions, i.e. simple values). So this proves my point - the unit parameter is unnecessary noise.

**Comment by moodmosaic** [comment]
Yes, I see what you mean. Thanks for providing examples. :+1: :rocket:
