### ISSUE TITLE
Paket.Restore.targets - check in or add to .gitignore

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#27]
I have an untracked file `.paket\Paket.Restore.targets`. We should either check this in or add it to .gitignore (I messed up #24 because of it).

**Comment by cmeeren** [comment]
According to https://github.com/fsprojects/Paket/issues/2840 (see recent title change) it seems it should be checked in.

**Comment by moodmosaic** [comment]
Let's follow the official instructions, then. :)

**Comment by cmeeren** [comment]
Sure. (Note I haven't delved into the discussion or any reasons why.)
