### ISSUE TITLE
Should we transfer this repo to hedgehogqa?

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog-experimental#34]
It may help people discover it more easily! I think anyone using fsharp-hedgehog at least ought to know about this repo and its auto gen capability.

The only 'requirement' is that at least @jacobstanley and/or myself would need to have push access. But don't let that scare you, we work via pull requests all the time.

**Comment by cmeeren** [comment]
Sure!

**Comment by moodmosaic** [comment]
:heart_eyes: — Great, let us know if you need any help.

**Comment by cmeeren** [comment]
I get this error:

> You don’t have the permission to create public repositories on hedgehogqa

**Comment by jacobstanley** [comment]
I've added you as an @hedgehogqa member so you should be able to transfer now

**Comment by cmeeren** [comment]
Done! (May take a few minutes to complete.)

**Comment by moodmosaic** [comment]
Welcome on board, @cmeeren :confetti_ball: :cocktail:
