### ISSUE TITLE
Use new Hedgehog logo in NuGet package

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/fsharp-hedgehog-experimental#35]
@cmeeren, do you think it'd be possible to use [the new Hedgehog logo](https://raw.githubusercontent.com/hedgehogqa/fsharp-hedgehog/master/img/hedgehog-logo.png) also in the Hedgehog.Experimental NuGet package?

![image](https://user-images.githubusercontent.com/287532/73524693-f1c98180-440d-11ea-8596-ee8e622b12dc.png)

**Comment by cmeeren** [comment]
Sure! Would you be able to create a PR to update the files [here](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/tree/master/img)?

**Comment by cmeeren** [comment]
In case it's relevant, it's referenced here:

https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/7ce6d6b2c8e294d78c2da7ab735086064dd2e2a8/src/Hedgehog.Experimental/Hedgehog.Experimental.fsproj#L11

**Comment by moodmosaic** [comment]
Hmm... We actually never updated those files. Instead we've added a new one called `hedgehog-logo.png` as you can see in https://github.com/hedgehogqa/fsharp-hedgehog/tree/master/img

If I go and upload that new file under `/img` and modify the `.fsproj` you'd have to make a new NuGet release in order to pick up the new image, I guess.

The other option would be to overwrite `SQUARE_hedgehog_300x300.png` but the new logo is 615x615 so the filename will no longer be accurate.

**Comment by cmeeren** [comment]
Could you make a 300x300 version so the existing/old nuget packages get the correct logo, and additionally upload the new file under `/img` and modify the `.fsproj` as you suggest?

**Comment by moodmosaic** [comment]
I can ask for it, yes, but that may take a while.

---

In the meantime, we can replace the image in `SQUARE_hedgehog_300x300.png` if that's OK for you?

**Comment by cmeeren** [comment]
> In the meantime, we can replace the image in `SQUARE_hedgehog_300x300.png` if that's OK for you?

Yes, that's exactly what I asked (in addition to your previous suggestion of uploading the new file and modify the `.fsproj`). I'm confused - what exactly did you mean could take a while?

**Comment by moodmosaic** [comment]
>what exactly did you mean could take a while?

Oh, I mean that I'd have to get @jacobstanley to ask Jessica Stanley to resize the image as she made the new logo. Unless you're good at Photoshop and know how to do it.

PR #36 should be OK for now, though.

**Comment by cmeeren** [comment]
Thanks! If you google "resize images" you find a plethora of free, online services for resizing/cropping images. :)

**Comment by moodmosaic** [comment]
Obviously, everyone's aware of that :smiley: The issue with most of those converters is that they also do a non-optimal resampling, most of the times, or some others even won't keep the transparency at all. YMMV, though.
