### ISSUE TITLE
AppVeyor missing access to hedgehogqa org

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#38]
@moodmosaic CI is not building. I think it's because AppVeyor doesn't have access to the hedgehogqa org. I have sent a request for access.

**Comment by moodmosaic** [comment]
I haven't signed-in on AppVeyor for the last month or so, but from what I see right now, also *fsharp-hedgehog* isn't listed there. For *fsharp-hedgehog* though we recently [switched to GitHub Actions](https://github.com/hedgehogqa/fsharp-hedgehog/pull/212/files) but *without* having to explicitly opt-out from AppVeyor.

![image](https://user-images.githubusercontent.com/287532/88545226-fa94bc00-d01a-11ea-97b8-6dc09b18777a.png)

**Comment by moodmosaic** [comment]
I can investigate this, however, do you also consider switching to GitHub Actions? (I don't see any request for access on AppVeyor.)

**Comment by cmeeren** [comment]
I'm open to GH actions, but I have never used it and can't find a way to keep the same behaviour (push to NuGet when tagged).

The request is pending, so someone should see something, but I have no idea who or where.

![image](https://user-images.githubusercontent.com/7766733/88567382-b237c700-d037-11ea-8096-69e0a81c161d.png)

**Comment by moodmosaic** [comment]
@jacobstanley can you check if there's an email?

**Comment by cmeeren** [comment]
I'm trying to set up GitHub actions now, but I can't access the repo settings to add the NuGet API key. Can you give me full access to this repo?

**Comment by moodmosaic** [comment]
Both AppVeyor and GitHub Action settings should be set now. Can you check?

**Comment by cmeeren** [comment]
AppVeyor still says "Access request pending", but I have successfully managed to publish a package using GitHub actions.

**Comment by moodmosaic** [comment]
Great! So there's no need for AppVeyor, then, right?

**Comment by cmeeren** [comment]
Correct.
