### ISSUE TITLE
Website - Old website link

### ISSUE THREAD

**Issue by ShalokShalom** [hedgehogqa/fsharp-hedgehog-experimental#39]
Hi - since I found no repo for the homepage, I will just post this here, in my favorite repo ;)

That link here directs to the old homepage, I imagine this is accidental? 

https://hedgehog.qa/
![Screenshot_2020-10-14-13-10-49-90](https://user-images.githubusercontent.com/6344099/95981605-30c62880-0e1f-11eb-9334-597842e23a4e.jpg)

**Comment by moodmosaic** [comment]
I think the homepage is fine since this repo is part of the core hedgehog org.

**Comment by ShalokShalom** [comment]
How you mean?

**Comment by cmeeren** [comment]
Sorry, I'm confused. Where does this issue belong? Should it be closed? Who should do what?

**Comment by moodmosaic** [comment]
> How you mean?

I mean that this repo *can* link to https://hedgehog.qa since it's *part* of Hedgehog.

**Comment by ShalokShalom** [comment]
Click on the marked spot on the homepage.
It takes you to an older version, I guess the URL behind that button is outdated.

**Comment by cmeeren** [comment]
@moodmosaic This isn't about this repo, it's about a bug on the homepage.

**Comment by moodmosaic** [comment]
I've no idea, @jacobstanley should know as he's the one maintaining the website.

**Comment by moodmosaic** [comment]
Thanks for pointing that out though, @ShalokShalom :+1:

**Comment by cmeeren** [comment]
Closing this and unsubscribing myself since it's not related to this repo, but feel free to continue the discussion.

**Comment by ShalokShalom** [comment]
Is the homepage open source? I would have contributed there, if there would be any mention anywhere about that

*shrug*

**Comment by moodmosaic** [comment]
@ShalokShalom, the website source code isn't on GitHub, but @jacobstanley should fix that link sooner or later. :+1:
