### ISSUE TITLE
Must AutoGenConfig be a struct?

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#44]
In commit b52c847a, I added `[<CLIMutable>]` and `[<Struct>]` to `AutoGenConfig`, with the motivation to make it easier to use from C#. I can understand how `CLIMutable` achieves that goal, but I can't figure out why `Struct` should make it easier.

Furthermore, since `AutoGenConfig` has so many fields, having it be a `Struct` seems like it could be bad for performance (I have not measured).

Could anyone illuminate me? Is `Struct` relevant for C# interop?

**Comment by cmeeren** [comment]
@moodmosaic @TysonMN any input on this?

**Comment by TysonMN** [comment]
I haven't done much C#/F# interop.  Sorry.

**Comment by moodmosaic** [comment]
IIRC, structs are allocated on thread-stack rather than the (managed) heap. I don't think we have to care about this upfront, so I'd rather remove that attribute. I would also remove the CLIMutable one, unless there's a reported issue.

IIRC, the CLIMutable adds (among others?) a default parameterless consturctor, making it friendlier to various (de)serializers.

**Comment by cmeeren** [comment]
AFAIK CLIMutable is nice for C# interop. Without it, a record has (in C#) a constructor that requires all parameters, and the parameters are read-only. With the attribute, one can set the record members after-the-fact as well as use object initialization syntax when creating it.

That said, I'm not using C#, so I'll leave the decision to you, @moodmosaic. If you still think it's better to remove CLIMutable, we can do that.

**Comment by TysonMN** [comment]
> AFAIK CLIMutable is nice for C# interop. Without it, a record has (in C#) a constructor that requires all parameters, and the parameters are read-only. With the attribute, one can set the record members after-the-fact as well as use object initialization syntax when creating it.

[C# 9 adds an `init` functionality to properties](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#init-only-setters) that handle this case well.

**Comment by cmeeren** [comment]
Yep, but the page doesn't say anything about whether it's supported for F# records.

**Comment by moodmosaic** [comment]
Unless there's a C# project inside the repo/solution that breaks without those attributes, or there's a reported issue asking to add any of them, to me it's just dead-code and I'd simply take them out...

**Comment by moodmosaic** [comment]
Alright, I looked into it as I was curious and it turns out that in order to do this in C#
```c#
var a = new AutoGenConfig();
```

You *either* want CliMutable or Struct; not both as the underlying IL shows:

```
// CliMutable
.class public auto ansi sealed serializable Hedgehog.AutoGenConfig
  extends [netstandard]System.Object
{
  .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CLIMutableAttribute::.ctor() = (
    01 00 00 00
  )
...
```

```
// Struct
.class public sequential ansi sealed serializable Hedgehog.AutoGenConfig
  extends [netstandard]System.ValueType
{
  .custom instance void [FSharp.Core]Microsoft.FSharp.Core.StructAttribute::.ctor() = (
    01 00 00 00
  )
...
```

I can't find a reason where we'd want to declare this as a Value Type allocated in managed heap (Struct) so I would leave CliMutable as-is but I would remove Struct, that is:

```diff
diff --git a/src/Hedgehog.Experimental/Gen.fs b/src/Hedgehog.Experimental/Gen.fs
index 7df2d9e..634820c 100644
--- a/src/Hedgehog.Experimental/Gen.fs
+++ b/src/Hedgehog.Experimental/Gen.fs
@@ -13,7 +13,7 @@ module AutoOverrides =
   let internal map f = unwrap >> f >> AutoOverrides


-[<CLIMutable; Struct>]
+[<CLIMutable>]
 type AutoGenConfig = {
   Byte : Gen<byte>
   Int16 : Gen<int16>
```
