### ISSUE TITLE
Support for Array.Rank greater than 1

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog-experimental#50]
Why isn't there support when [`Array.Rank`](https://docs.microsoft.com/en-us/dotnet/api/system.array.rank) is greater than `1`?  Is there some fundamental technical difficulty or is it just that sufficient time/effort was never spent to implement that case?

https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/439159cd7cbf99b793bae3eac59dd02a9192d7a8/src/Hedgehog.Experimental/Gen.fs#L421-L431

**Comment by cmeeren** [comment]
> is it just that sufficient time/effort was never spent to implement that case

The `auto` code originally came from elsewhere, so I'm not sure, but at least from my perspective, this is correct. Feel free to create a PR with this functionality!
