### ISSUE TITLE
Does Hedgehog return an incorrect value on failure?

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog-experimental#52]
I am running a test with a simple condition:

```fsharp
match message with
| Happy s when s.Reason.Contains('a') -> Nack
| _ -> Ack
```

I see in debug that it fails properly and the value is shrunk properly to the failure case of a single `a` character (see the screenshot)

![image](https://user-images.githubusercontent.com/1394391/131456018-79a9ad8a-42a4-4b29-ac3f-e74492d61268.png)

I also see in debug that this is the last shrink, i.e. the test is not getting called anymore.

However, the result of the test is printed as:

```
*** Failed! Falsifiable (after 68 tests and 6 shrinks):
[Happy { "reason": "`", "level": -287093 }]
```

Or see this screenshot
![image](https://user-images.githubusercontent.com/1394391/131456413-2ca8fcc9-93bd-4104-9e68-03243bf6bfbd.png)

Which is not a correct failing condition, it should say `"reason": "a"` instead!

Interestingly, I also have a numeric field in that structure, and when I do something like

```fsharp
| Happy s when s.Level = 97 -> Nack
```

Then the failure is reported correctly. So it looks like it is working for numbers, but not for strings

**Comment by moodmosaic** [comment]
> @moodmosaic, can you transfer this issue to [fsharp-hedgehog-experimental](https://github.com/hedgehogqa/fsharp-hedgehog-experimental)?

Done

**Comment by TysonMN** [comment]
I thought I linked this issue to PR #51 but clearly not since it is still open.

This issue should be closed.

**Comment by AlexeyRaga** [comment]
@TysonMN thanks a lot for fixing it so quickly!!

**Comment by TysonMN** [comment]
My pleasure. Thanks for the initial report and helping me by answering my questions.
