### ISSUE TITLE
Add support to Nullable<T>

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog-experimental#65]
Do you think that support for `Nullable<'T>` can be added, similarly to how `Option<'T>` is now supported?
It is useful for property-testing with types that are defined in C#.

**Comment by TysonMN** [comment]
Yes, this is a good idea.

Can you contribute a PR for it?

**Comment by AlexeyRaga** [comment]
Challenge accepted! :)
Please have a look at PR #66

**Comment by AlexeyRaga** [comment]
@TysonMN can we have a Nuget release with this fix?

**Comment by dharmaturtle** [comment]
Genuine, unassuming question: do we want to wait for https://github.com/hedgehogqa/fsharp-hedgehog-experimental/pull/67 or is this time sensitive?

**Comment by AlexeyRaga** [comment]
Would be nice to have it if possible, yes. It is also unrelated to #67, so we can make another release after.
But if you prefer to wait until #67 is settled then it should also be fine, I'm trying to get through it asap.

**Comment by TysonMN** [comment]
I was planning on releasing after PR #67 is complete.

**Comment by TysonMN** [comment]
First included in [version 0.6.1](https://www.nuget.org/packages/Hedgehog.Experimental/0.6.1)
