### ISSUE TITLE
Update NuGet API key

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#70]
It has been a while since I have been a maintainer of this package, but I just noticed that NuGet publishes are still done in my name, presumably because it's using my API key:

<img width="691" alt="image" src="https://user-images.githubusercontent.com/7766733/179424413-2fac5003-352b-40c4-9fd7-bbca9f8c42c2.png">

@TysonMN, I understand you to be the current primary maintainer of this package. I have just added you as an owner of the NuGet package. Whenever it's convenient for you, consider creating and using your own API key and removing me as a NuGet package owner.

**Comment by TysonMN** [comment]
I am now a (co) owner the NuGet package, and this repo is now using my API key.

Thanks @cmeeren :)

**Comment by cmeeren** [comment]
Thanks! I have now removed myself as an owner of the package.
