### ISSUE TITLE
Add permutation generators

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog-experimental#9]
It'd be nice with generators that permute existing sequences/lists/strings:

```f#
/// Generates a permutation the specified list (shuffles its elements).
permutationOf (list : 'a list) : Gen<'a list>

/// Randomizes the case of the characters in the string.
casePermutationOf (str : string) : Gen<string> =
```

See the combinators removed in [this commit](https://github.com/hedgehogqa/fsharp-hedgehog/pull/140/commits/dda4bfea67c3f00537d7381de8f1f6657bce8a3f). An open question is how to handle the randomness generation - System.Random might not be the correct choice.

**Comment by moodmosaic** [comment]
Hmm, we may as well name these `shuffle` and `caseShuffle` after QuickCheck:

```
seq<'a> -> Gen<seq<'a>>
```

It was added in QuickCheck version [2.8.0](https://hackage.haskell.org/package/QuickCheck-2.8/docs/src/Test-QuickCheck-Gen.html#shuffle) and got further optimized in version [2.8.2](https://github.com/nick8325/quickcheck/commit/6c360c1b594b0243e51bfcd4e2428882570e7a51).

If you want to look at a few ways of implementing this, in the past I've added [Gen.shuffle to FsCheck, based on QuickCheck](https://github.com/fscheck/FsCheck/pull/221/commits/3347ebdb36e270a9b8b65911a982771a30436b3c). (Though, we ended up doing it [à la Fisher-Yates](https://github.com/fscheck/FsCheck/pull/221/commits/a9af0aecd97edb329a08a29b2f713bb8b776555f).)

**Comment by cmeeren** [comment]
I agree on naming then `shuffle` and `caseShuffle`.

I did do it using Fisher-Yates in the original commit. But `System.Random` was still used as the random generator. I am unsure if that is acceptable for Hedgehog (I expect not, since there seems to be a fairly elaborate random number thingy in place - if it is in fact unnecessary, we could probably save quite a bit of performance by using System.Random).

I like your original FsCheck implementation; generating a list of sort keys seems like a safe way to do it while using whatever randim generators are already in place. But why did you change to Fisher-Yates? Performance?

**Comment by moodmosaic** [comment]
I will try to explain the philosophy behind Hedgehog's PRNG tomorrow. It's certainly not a leftover; it's actually better than QuickCheck's if I dare to say so.

(On mobile right now, hence the brevity.)

**Comment by moodmosaic** [comment]
>But why did you change to Fisher-Yates? Performance?

Yes, in FsCheck, @kurtschelfthout suggested Fisher-Yates because of that (performance). Look around https://github.com/fscheck/FsCheck/pull/221/commits/a9af0aecd97edb329a08a29b2f713bb8b776555f

**Comment by moodmosaic** [comment]
>I did do it using Fisher-Yates in the original commit. But `System.Random` was still used as the random generator.

If you did it this way, it should be perfectly fine―but instead of using `System.Random` you should use `Gen.integral`.

Internally, Hedgehog uses [SplitMix](http://gee.cs.oswego.edu/dl/papers/oopsla14.pdf) as the PRNG, and while we haven't (yet) run [statistical tests](https://en.wikipedia.org/wiki/Diehard_tests) against it, its behavior is [documented](http://gee.cs.oswego.edu/dl/papers/oopsla14.pdf).

**Comment by cmeeren** [comment]
I have previously skimmed parts of that paper but it was a bit too technical for me. Could I ask you to briefly explain why Hedgehog can't use System.Random?

Also, I'll create a PR using Gen.integral.

**Comment by cmeeren** [comment]
> It shouldn't use `System.Random` as that's a different PRNG from the one that's currently used.

Sorry, I wasn't clear enough: I'll of course use `Gen.integral`, but I was wondering what the reason is for Hedgehog **as a whole** using SplitMix and not System.Random. Especially since I think (based on some *very* cursory testing done a while back) that System.Random could significantly improve performance.

**Comment by moodmosaic** [comment]
Can you even create arbitrarily large signed integers and 64-bit signed integers with `System.Random`?

**Comment by cmeeren** [comment]
[Apparently](https://encrypted.google.com/search?hl=en&q=system.random%20bigint), but it's not trivial and there are pitfalls to avoid (e.g. biases, performance). Still, I'd guess that performance for BigInts is not particularly useful for most Hedgehog users (I might be wrong).

**Comment by moodmosaic** [comment]
FWIW, [here](https://github.com/hedgehogqa/haskell-hedgehog/blob/891b67c85d637441e76a0151ac02f1eb63006a05/hedgehog/src/Hedgehog/Internal/Gen.hs#L1502-L1512) is `shuffle` in the Haskell version of Hedgehog.
